<?xml version="1.0" encoding="UTF-8"?>
<!--
     Attention: Generated code! Do not modify by hand!
     Generated by: hibernate.hbm.xml.vsl in andromda-hibernate-cartridge.
  -->
<!DOCTYPE hibernate-mapping PUBLIC "-//Hibernate/Hibernate Mapping DTD 3.0//EN"
          "http://hibernate.sourceforge.net/hibernate-mapping-3.0.dtd">

<hibernate-mapping default-cascade="none">
    <class name="com.oatsystems.udm.audit.AtExWarningsDetailImpl" table="at_ex_warnings_detail" dynamic-insert="false" dynamic-update="false">
        <id name="atExWarningsDetail" type="java.lang.Long" unsaved-value="null">
            <column name="at_ex_warnings_detail_id" sql-type="INTEGER"/>
            <generator class="native">
            </generator>
        </id>
        <property name="tableName" type="java.lang.String">
            <column name="table_name" not-null="false" unique="false" sql-type="NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CS_AS"/>
        </property>
        <property name="tablePk" type="java.lang.Long">
            <column name="table_pk" not-null="false" unique="false" sql-type="INTEGER"/>
        </property>
        <property name="deleted" type="true_false">
            <column name="deleted" not-null="false" unique="false" sql-type="CHAR(1)"/>
        </property>
        <many-to-one name="auditTrailException" class="com.oatsystems.udm.audit.AuditTrailExceptionImpl" foreign-key="atExWarningDtl_fk1" lazy="proxy" fetch="select">
            <column name="audit_trail_exception_id" not-null="false" sql-type="INTEGER"/>
        </many-to-one>
    </class>
</hibernate-mapping>